import React from 'react';

const AboutPage: React.FC = () => {
  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="card">
        <div className="card-header">
          <h3 className="card-title">Privacy Policy</h3>
          <p className="card-description">Last Updated: October 1, 2025</p>
        </div>
        <div className="card-content space-y-6 text-gray-300">
          <section>
            <h4 className="text-xl font-semibold text-white mb-3">Interpretations and Definitions</h4>
            
            <h5 className="text-lg font-semibold text-white mb-2">Interpretation</h5>
            <p className="mb-4">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. 
              The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h5 className="text-lg font-semibold text-white mb-2">Definitions</h5>
            <p className="mb-2">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li><strong className="text-white">Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong className="text-white">Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong className="text-white">Application</strong> refers to Win5x, the software program provided by the Company.</li>
              <li><strong className="text-white">Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Win5x.</li>
              <li><strong className="text-white">Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong className="text-white">Country</strong> refers to the jurisdiction where Win5x operates.</li>
              <li><strong className="text-white">Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong className="text-white">Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong className="text-white">Service</strong> refers to the Application.</li>
              <li><strong className="text-white">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong className="text-white">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong className="text-white">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </section>

          <section>
            <h4 className="text-xl font-semibold text-white mb-3">Collecting and Using Your Personal Data</h4>
            
            <h5 className="text-lg font-semibold text-white mb-2">Types of Data Collected</h5>
            
            <h6 className="font-semibold text-white mb-2">Personal Data</h6>
            <p className="mb-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul className="list-disc pl-6 space-y-1 mb-4">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Usage Data</li>
            </ul>

            <h6 className="font-semibold text-white mb-2">Usage Data</h6>
            <p className="mb-4">
              Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="mb-4">
              When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            </p>

            <h6 className="font-semibold text-white mb-2">Tracking Technologies and Cookies</h6>
            <p className="mb-4">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
            </p>
          </section>

          <section>
            <h4 className="text-xl font-semibold text-white mb-3">Use of Your Personal Data</h4>
            <p className="mb-2">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li><strong className="text-white">To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
              <li><strong className="text-white">To manage Your Account</strong>: to manage Your registration as a user of the Service.</li>
              <li><strong className="text-white">For the performance of a contract</strong>: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
              <li><strong className="text-white">To contact You</strong>: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
              <li><strong className="text-white">To provide You</strong> with news, special offers and general information about other goods, services and events which we offer.</li>
              <li><strong className="text-white">To manage Your requests</strong>: To attend and manage Your requests to Us.</li>
            </ul>
          </section>

          <section>
            <h4 className="text-xl font-semibold text-white mb-3">Retention of Your Personal Data</h4>
            <p className="mb-4">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>
          </section>

          <section>
            <h4 className="text-xl font-semibold text-white mb-3">Transfer of Your Personal Data</h4>
            <p className="mb-4">
              Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
            </p>
          </section>

          <section>
            <h4 className="text-xl font-semibold text-white mb-3">Disclosure of Your Personal Data</h4>
            
            <h6 className="font-semibold text-white mb-2">Business Transactions</h6>
            <p className="mb-4">
              If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
            </p>

            <h6 className="font-semibold text-white mb-2">Law Enforcement</h6>
            <p className="mb-4">
              Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.
            </p>
          </section>

          <section>
            <h4 className="text-xl font-semibold text-white mb-3">Security of Your Personal Data</h4>
            <p className="mb-4">
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </section>

          <section>
            <h4 className="text-xl font-semibold text-white mb-3">Children's Privacy</h4>
            <p className="mb-4">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
            </p>
          </section>

          <section>
            <h4 className="text-xl font-semibold text-white mb-3">Links to Other Websites</h4>
            <p className="mb-4">
              Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
            </p>
          </section>

          <section>
            <h4 className="text-xl font-semibold text-white mb-3">Changes to this Privacy Policy</h4>
            <p className="mb-4">
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top of this Privacy Policy.
            </p>
          </section>

          <section>
            <h4 className="text-xl font-semibold text-white mb-3">Contact Us</h4>
            <p>If you have any questions about this Privacy Policy, You can contact us through our support channels within the Win5x application.</p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default AboutPage;
